### ISSUE TITLE
ThePen makes taskbar disappear on main monitor when alt+tabbing out of borderless windowed games

### ISSUE THREAD

**Issue by AstudilloMarillo** [ladofa/thepen#7] opened 2024-02-03 10:20 UTC
I was having this issue for the last weeks where I would alt+tab out of a game and my Windows Taskbar would disappear. After troubleshooting for what seems like an eternity, I finally figured out ThePen is the culprit. Probably the transparent overlay causing this. It only happens when I have a game in borderless windowed full screen, but I run all my games like that. Any way you could fix this?

**Comment by ladofa** [comment] 2024-02-04 05:53
Honestly says, at the first time in developing, I tried to make the taskbar disappeared in all times. But I didn't know why and when it works or not, and didn't give a care.
Now the taskbar is needed, i will find and delete all tries to disappear the taskbar. It will be updated soon.

**Comment by AstudilloMarillo** [comment] 2024-02-26 17:10
Did you manage to make any progress on this by any chance? (No rush, just excited and curious)

**Comment by ladofa** [comment] 2024-02-28 14:46
> Did you manage to make any progress on this by any chance? (No rush, just excited and curious)

Really sorry about it, I'm going through very busy days, I will find the way from the beginning of May 24. 
Hugely thank you for your care!

**Comment by AstudilloMarillo** [comment] 2024-03-01 16:35
> Really sorry about it, I'm going through very busy days, I will find the way from the beginning of May 24. Hugely thank you for your care!

That's completely fine, I'll be patient.

**Comment by ladofa** [comment] 2024-03-02 06:55
I'm really happy to open the result and close this issue. See the alpah8 version.

**Comment by AstudilloMarillo** [comment] 2024-03-02 13:08
> I'm really happy to open the result and close this issue. See the alpah8 version.

I'm afraid it's the same result with alpha8. Still no taskbar when alt+tabbing out of a full screen borderless window game. Not sure if my monitor resolution (1440p) could be the cause?

**Comment by ladofa** [comment] 2024-03-02 13:41
I might misss-understand your issue.

I understood your problem is like this - 1. play any full screen game 2. alt+tab 3. ThePen program doesn't appear on your taskbar. And I truly fixed it on alpah8, and stupidly proud of the job. But now I read yours again, I realized that you are about the taskbar itself. ThePen already had a problem that the title of this program goes disappeared in the taskbar occationally (It was well known for me). So I thought you are saying about my issue.  And my poor English helped my missunderstanding. Really sorry about that.

I couldn't imagine anyone caring about it. But thankfully I succeeded in reproducing and confirming the bug you said on **my computer**, with my game - Vampire Survivor. When ThePen is running, Vampire Survivor is running and alt+tab, the taskbar was not shown, ThePen may make some difference, I checked.

Becouse I never thought about it, finding the reason and fixing may take long time or be impossible. But I can say I'm spending time trying to solve this problem without leaving it as it is. Sorry for I have to say like this.

**Comment by ladofa** [comment] 2024-03-02 14:21
I might clear it. Can you check this version?
[thepen-alpha9.zip](https://github.com/ladofa/thepen/files/14469672/thepen-alpha9.zip)

**Comment by AstudilloMarillo** [comment] 2024-03-02 14:34
> I might misss-understand your issue.
> 
> I understood your problem is like this - 1. play any full screen game 2. alt+tab 3. ThePen program doesn't appear on your taskbar. And I truly fixed it on alpah8, and stupidly proud of the job. But now I read yours again, I realized that you are about the taskbar itself. ThePen already had a problem that the title of this program goes disappeared in the taskbar occationally (It was well known for me). So I thought you are saying about my issue. And my poor English helped my missunderstanding. Really sorry about that.
> 
> I couldn't imagine anyone caring about it. But thankfully I succeeded in reproducing and confirming the bug you said on **my computer**, with my game - Vampire Survivor. When ThePen is running, Vampire Survivor is running and alt+tab, the taskbar was not shown, ThePen may make some difference, I checked.
> 
> Becouse I never thought about it, finding the reason and fixing may take long time or be impossible. But I can say I'm spending time trying to solve this problem without leaving it as it is. Sorry for I have to say like this.

I understand that this is a very niche issue, and that I might be the only one to care about this. So it's really nice of you to put in the effort in spite of that. Also, I understand the language barrier can create misunderstandings, no need to apologize, you're doing great.


> I might clear it. Can you check this version? [thepen-alpha9.zip](https://github.com/ladofa/thepen/files/14469672/thepen-alpha9.zip)

Yes!! You managed to fix it! I'm very happy with this, thanks a lot for making the time, I really appreciate it. I'll definitely be using ThePen even more now 😄!

**Comment by ladofa** [comment] 2024-03-03 11:37
I'm really happy to hear that! Let me know any other request. Good luck!

**Closed as completed** 2024-03-03 11:38 UTC
Labels: bug
